name: Actions CI Test
on: [push]
jobs:
        Build-Project:
                runs-on: ubuntu-latest
                steps:
                        - run echo "Build of {{github-repository}} started ..."
